# Simple test pipeline for debugging microbatch
pipeline_name: test_simple_ab
tags: [test, debug]

variables:
  microbatch:
    event_time_column: "event_date"
    batch_size: "day"
    lookback: 0
    begin: "2025-07-01 00:00:00"
    end: "2025-07-01 23:59:59"
  exp_id: "test_experiment"

steps:
  - id: generate_data
    type: source
    source_type: csv
    config:
      file_path: data/test_data.csv

  - id: run_ttest
    type: processor
    processor_type: ab_testing
    depends_on: [generate_data]
    config:
      test_type: ttest
      metric_column: gross_revenue
      group_column: group
      alpha: 0.05
      test_direction: relative
      calculate_mde: true
      power: 0.8

  - id: save_results
    type: endpoint
    endpoint_type: csv
    depends_on: [run_ttest]
    config:
      file_path: output/simple_ab_test_results.csv